name: Generate GH Pages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dokka:
    name: Build module and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Generate Dokka Page
        run: ./gradlew dokkaHtmlMultiModule

      - name: Publish Page
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: build/dokka/dokkaHtmlMultiModule
          keep_history: true
  
